<?php
require_once __DIR__ . '/../auth/check_auth.php';
restrictTo(['admin']);
$summary = $pdo->query("SELECT k.kode_kelas, m.nama_matkul, k.jumlah_mahasiswa, u.nama_lengkap AS dosen FROM kelas k JOIN matakuliah m ON k.matakuliah_id=m.id LEFT JOIN dosen d ON k.dosen_id=d.id LEFT JOIN users u ON d.user_id=u.id ORDER BY k.kode_kelas")->fetchAll();
?>
<!DOCTYPE html><html lang="id"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title>Reports</title><link rel="stylesheet" href="../assets/css/app.css"><script src="../assets/js/app.js" defer></script></head>
<body><?php include __DIR__ . '/../components/sidebar.php'; ?><div class="main-content"><?php include __DIR__ . '/../components/header.php'; ?><main class="page-container">
<div class="page-header"><div><h1 class="page-title">Reports</h1><p class="page-subtitle">Charts, filters, and export preview.</p></div><div><button class="btn-secondary">Export Excel</button> <button class="btn-primary">Export PDF</button></div></div>
<div class="split-grid"><div class="card"><h3 class="card-title">Filter Laporan</h3><form class="form-stack"><select><option>Rekap Absensi Global</option><option>Rekap Nilai Akhir Per Kelas</option><option>Log Keaktifan Mengajar Dosen</option></select><select><option>Semester 1 - 2025/2026</option></select><button class="btn-primary">Preview</button></form></div><div class="card col-span-2"><h3 class="card-title">Activity Chart</h3><div class="chart-box"><div class="bar" style="height:50%"></div><div class="bar" style="height:75%"></div><div class="bar" style="height:42%"></div><div class="bar" style="height:90%"></div><div class="bar" style="height:65%"></div></div></div></div>
<div class="card"><h3 class="card-title">Live Preview Data</h3><div class="table-wrap"><table><thead><tr><th>Kelas</th><th>Mata Kuliah</th><th>Dosen</th><th>Mahasiswa</th></tr></thead><tbody><?php foreach ($summary as $s): ?><tr><td><?= htmlspecialchars($s['kode_kelas']) ?></td><td><?= htmlspecialchars($s['nama_matkul']) ?></td><td><?= htmlspecialchars($s['dosen'] ?? '-') ?></td><td><?= $s['jumlah_mahasiswa'] ?></td></tr><?php endforeach; ?></tbody></table></div></div>
</main></div></body></html>
